### PR TITLE
Adding a new AI comedian

### PR DESCRIPTION
**Pull request by nka-coder**
This is my comedian for the AI comedy scene. It also serves to demonstrate my coding skill for Konfuzio job application.

### CODE REVIEW

**Comment by atraining** [comment]
Hi @nka-coder 


I noticed that you recently closed the pull request. Were you able to schedule a meeting with our CTO?

[GitHub Repository: Contribute and Apply for a Job at Konfuzio AI Comedy Club](https://github.com/konfuzio-ai/ai-comedy-club#contribute-and-apply-for-a-job-)

I'm concerned that the PR may have been overlooked due to the holiday season. If that's the case, I apologize for the inconvenience.

Best 

Chris

**Comment by nka-coder** [comment]
Dear Christopher,
I didn't have the chance to talk to the CTO.

Best wishes,
Adamou
________________________________

**Comment by atraining** [comment]
Hi there, can you please review it. It includes py Cache 🙃

Adamou Nchange Kouotou ***@***.***> schrieb am Mo., 4. Sept.
2023, 13:48:

**Comment by nka-coder** [comment]
Noted. I will remove pycache and re-submit the PR.

________________________________

**Pull request closed without merging**
