### PR TITLE
Add my jokes

### PR DESCRIPTION
**Pull request by XinyueZ**
Pls take care of it
 
 
joke_bot

### CODE REVIEW

**Comment by atraining** [comment]
Hi @XinyueZ 

how should we deal with the URL https://dl.dropboxusercontent.com/scl/fi/n8bz45wkumy4vydhmcatk/open-ai-key-code-chan.txt?rlkey=v67srbojnb0nk3zkjzi1ycoqv ? 

Is there any way your bot will work in the pipeline with all other comedians?

Please reopen the PR if you think there is a way that your comedian can perform with all the others.

Best

Chris

**Comment by XinyueZ** [comment]
You should provide your openai key in a text file, just single  line, and replace the URL in the PR.

**Comment by atraining** [comment]
Hi @XinyueZ 

we can only run PRs in the pipeline if they can perform with all other bots.

So it's not possible without sharing the Key with all actors to add your bot to the panel.

Do you see any other option or would you be willing to replace the Open AI API driven model with something that can work indepentently?

Best

Chris

**Comment by XinyueZ** [comment]
When you already have the open ai key in your environment, it should work.

**Comment by atraining** [comment]
I mean can you please provide an comedian that works stand alone 😉

ChrisDEV ***@***.***> schrieb am Mi., 20. Sept. 2023, 18:22:

**Pull request closed without merging**
