### PR TITLE
jobApplication(Konfuzio): AI Python Developer / AI Engineer

### PR DESCRIPTION
**Pull request by lucchesi-rodrigo**
Following the steps on: https://join.com/companies/konfuzio/9111599-ai-python-developer-ai-engineer-or-join-a-100-product-driven-remote-team?pid=d7cb2e8e859c62cd7f75#:~:text=Please%20apply%20by,ai%2Dcomedy%2Dclub

### CODE REVIEW

**Comment by atraining** [comment]
Hi Rodrigo,

did you already sent us a short video to complete your application.

Best

Chris

Rodrigo Lucchesi ***@***.***> schrieb am Do., 14. Sept. 2023,
17:48:

**Comment by lucchesi-rodrigo** [comment]
Hi @atraining ,

I closed the previous PR in order to open a new one [link](https://github.com/konfuzio-ai/ai-comedy-club/pull/50). I forgot to send you the short video. Could you please provide me with an email address where I can send it to you? I'm also attaching my LinkedIn [profile](https://www.linkedin.com/in/rodrigo-lucchesi/).

Best!

**Comment by atraining** [comment]
Hi @lucchesi-rodrigo!

Thanks for your reply. Here you find the steps to proceed. Looking forward to the results.

https://github.com/konfuzio-ai/ai-comedy-club#contribute-and-apply-for-a-job-

**Comment by lucchesi-rodrigo** [comment]
Hi @atraining,

I sent the video and chose September 26th for our conversation. In the meantime, if you have anything to share with me, please feel free to reach out to me.

Best!

**Pull request closed without merging**
