### PR TITLE
adding DharaniKS folder and joke.py and test_joke.py files

### PR DESCRIPTION
**Pull request by DharaniKS098**
Hello,
As per the instructions, I have written the code to generate joke. Please review and give feedback, so that I can correct the mistakes and learn from it. 
Thanks for the opportunity.

Thanks,
Dharani K S

### CODE REVIEW

**Comment by DharaniKS098** [comment]
Hello,
As per the instructions, I have written the code to generate joke. Please review and give feedback, so that I can correct the mistakes and learn from it.
Thanks for the opportunity.

Thanks,
Dharani K S

**Comment by atraining** [comment]
Hi! Will you want to apply via this PR?

DharaniKS098 ***@***.***> schrieb am Do., 14. Sept. 2023,
15:45:

**Comment by DharaniKS098** [comment]
Yes, please proceed.

**Comment by atraining** [comment]
Can you please upload a video, you find the link to submit the video in the
readme.

DharaniKS098 ***@***.***> schrieb am Fr., 15. Sept. 2023,
21:04:

**Comment by atraining** [comment]
Hi @DharaniKS098 

Were you able to schedule a meeting with our CTO?

Here you find a detailed plan: [GitHub Repository: Contribute and Apply for a Job at Konfuzio AI Comedy Club](https://github.com/konfuzio-ai/ai-comedy-club#contribute-and-apply-for-a-job-)

I'm concerned that the PR may have been overlooked due to the holiday season. If that's the case, I apologize for the inconvenience.

Best

Chris

**Comment by DharaniKS098** [comment]
Dear Chris,
For your kind information, I attended the meeting yesterday at 4.30 PM.


Thanks,
Dharani K S

**Pull request merged**
